version: "3.6"
services:
    selenium:
        image: selenium/hub
        container_name: shoppinglist-selenium
        ports:
            - 4444:4444
        environment:
            GRID_MAX_SESSION: 10
    chrome:
        image: selenium/node-chrome
        depends_on: 
            - selenium
        environment:
            HUB_HOST: shoppinglist-selenium
            NODE_MAX_INSTANCES: 5
            NODE_MAX_SESSION: 5
    
